name: Development
on:
  push:

jobs:
  deploy:
    name: Deploy functions to Firebase (Development environment)
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: diple-app-dev
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: npm install
        run: |
          npm install
        env:
          CI: true
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
